### ISSUE TITLE
Discussion for "Hello World"

### ISSUE THREAD

**Issue by nchlswhttkr** [nchlswhttkr/nchlswhttkr.github.io#5]
This issue thread can be used to leave comments on https://nchlswhttkr.com/blog/hello-world!

It's powered by https://utteranc.es/, and you can comment below!

**Comment by nchlswhttkr** [comment]
Hello World! 🔮

**Comment by ericjiang97** [comment]
I see you have commenting too on your blog posts :thinking:

**Comment by ericjiang97** [comment]
![](https://media.giphy.com/media/slVWEctHZKvWU/source.gif)

GIFs also works!

**Comment by only-noike** [comment]
Gee whiz, comments! :O
